# Name: Woju CI/CD for woju-monorepo
name: CI/CD for woju-monorepo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server:
          - server_user
          # - server_item

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Decrypt .env.enc
        run: openssl aes-256-cbc -d -pbkdf2 -in .env.enc -out .env -k ${{ secrets.PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create and use a new builder
        run: docker buildx create --use

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./packages/${{ matrix.server }}
          file: ./packages/${{ matrix.server }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/woju-${{ matrix.server }}:latest

      - name: Deploy Docker Image to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.RELEASE_SERVER_HOST }}
          username: ${{ secrets.RELEASE_SERVER_USER }}
          password: ${{ secrets.RELEASE_SERVER_PASSWORD }}
          port: ${{ secrets.RELEASE_SERVER_PORT }}
          script: |
            cd ~/woju-server
            docker-compose pull ${{ matrix.server }}
            docker-compose up -d ${{ matrix.server }}